apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: hybris-controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hybris-controller-manager
  namespace: system
  labels:
    control-plane: hybris-controller-manager
spec:
  selector:
    matchLabels:
      control-plane: hybris-controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: hybris-controller-manager
    spec:
      containers:
      - command:
        - /manager
        image: quay.io/redhat-sap-cop/hybris-operator:0.0.4
        imagePullPolicy: Always
        name: manager
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
        env:
          - name: WATCH_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 10
