apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "hybris.hybris.org/v1alpha1",
          "kind": "HybrisApp",
          "metadata": {
            "name": "hybrisapp-sample"
          },
          "spec": {
            "baseImageName": "hybris-base",
            "baseImageTag": "v0.1",
            "sourceRepoRef": "master",
            "sourceRepoURL": "https://github.com/redhat-sap/sap-commerce-app-example.git"
          }
        },
        {
          "apiVersion": "hybris.hybris.org/v1alpha1",
          "kind": "HybrisBase",
          "metadata": {
            "name": "hybrisbase-sample"
          },
          "spec": {
            "URL": "http://nexus.redhat.com/nexus/service/local/repositories/releases/content/org/hybris/hybris/1.0/hybris-1.0.tar.gz",
            "imageName": "hybris-base",
            "imageTag": "v0.1",
            "jdkURL": "https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.5/sapmachine-jdk-11.0.5-1.x86_64.rpm",
            "password": "admin123",
            "username": "admin"
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: sap-commerce-operator.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HybrisApp is the Schema for the hybrisapps API
      displayName: Hybris App
      kind: HybrisApp
      name: hybrisapps.hybris.hybris.org
      version: v1alpha1
    - description: HybrisBase is the Schema for the hybrisbases API
      displayName: Hybris Base
      kind: HybrisBase
      name: hybrisbases.hybris.hybris.org
      version: v1alpha1
  description: Sap Commerce Operator description. TODO.
  displayName: Sap Commerce Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: default
      deployments:
      - name: sap-commerce-operator-hybris-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: hybris-controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: hybris-controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --metrics-addr=127.0.0.1:8080
                - --enable-leader-election
                command:
                - /manager
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                image: quay.io/redhat-sap-cop/hybris-operator:0.1
                imagePullPolicy: IfNotPresent
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        - apiGroups:
          - apps.openshift.io
          resources:
          - deploymentconfigs
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - build.openshift.io
          resources:
          - buildconfigs
          - builds
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - configmaps
          - secrets
          - services
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hybris.hybris.org
          resources:
          - hybrisapps
          - hybrisapps/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hybris.hybris.org
          resources:
          - hybrisapps/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - hybris.hybris.org
          resources:
          - hybrisbases
          - hybrisbases/finalizers
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - hybris.hybris.org
          resources:
          - hybrisbases/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - image.openshift.io
          resources:
          - imagestreams
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - route.openshift.io
          resources:
          - routes
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sap-commerce-operator
  links:
  - name: Sap Commerce Operator
    url: https://sap-commerce-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.1
