apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: sap-commerce-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: HybrisApp is the Schema for the hybrisapps API
      displayName: Hybris App
      kind: HybrisApp
      name: hybrisapps.hybris.hybris.org
      version: v1alpha1
    - description: HybrisBase is the Schema for the hybrisbases API
      displayName: Hybris Base
      kind: HybrisBase
      name: hybrisbases.hybris.hybris.org
      version: v1alpha1
  description: Sap Commerce Operator description. TODO.
  displayName: Sap Commerce Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - sap-commerce-operator
  links:
  - name: Sap Commerce Operator
    url: https://sap-commerce-operator.domain
  maintainers:
  - email: your@email.com
    name: Maintainer Name
  maturity: alpha
  provider:
    name: Provider Name
    url: https://your.domain
  version: 0.0.0
